server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cinema_management"
    username: "root"
    password: "root"

  mail:
    host: smtp.gmail.com
    port: 587
    username: lphceu17@gmail.com
    password: hmkq exip kliq qmya
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  signerKey: "b66eaccd1728dc30de5ce144e38da4e3b4b289a719e794b0db188f3967f1a0b5"
  valid-duration: 3600
  refreshable-duration: 604800

app:
  mail:
    sender:
      email: no-reply@cinemabookingbcp.com
      name: Movie Booking System